# Generated by Django 3.2.12 on 2022-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('user_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('venue_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('overview', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('citation', models.URLField(blank=True, null=True)),
                ('pdf', models.URLField(blank=True, null=True)),
                ('supplement', models.URLField(blank=True, null=True)),
                ('slides', models.URLField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('code', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='repository.Author')),
                ('categories', models.ManyToManyField(to='repository.Category')),
                ('venue', models.ManyToManyField(blank=True, default='', to='repository.Venue')),
            ],
        ),
    ]
