# Generated by Django 3.2.12 on 2023-02-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_conference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='conference',
        ),
    ]
