# Generated by Django 3.2.12 on 2023-02-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_delete_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('link', models.URLField(max_length=5000)),
                ('location', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
